- name: Install AWS Configuration
  hosts: all
  become: yes
  vars:
    aws_access_key: ""
    aws_secret_key: ""
    aws_region: "us-east-1"

  tasks:
  - name: Install unzip
    apt:
      name: unzip
      state: present

  - name: Download AWS CLI v2 installer
    get_url:
      url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      dest: "/tmp/awscliv2.zip"

  - name: unzip aws cli installer
    unarchive:
      src: "/tmp/awscliv2.zip"
      dest: "/tmp/"
      remote_src: yes

  - name: Install aws cli system
    shell: |
      /tmp/aws/install
    args:
      creates: /usr/local/bin/aws
  
  - name: Ensure .aws directory exists
    file:
      path: "/home/ubuntu/.aws"
      state: directory
      owner: ubuntu
      mode: '0700'

  - name: create aws credentials file
    copy:
      dest: "/home/ubuntu/.aws/credentials"
      content: |
       [default]
       aws_access_key_id = {{ aws_access_key }}
       aws_secret_access_key = {{ aws_secret_key }}
      owner: ubuntu
      group: ubuntu
      mode: '0600'

  - name: Create AWs config file
    copy:
      dest: "/home/ubuntu/.aws/config"
      content: |
       [default]
       region= {{ aws_region }} 
       output=json
      owner: ubuntu
      group: ubuntu
      mode: "0600"

  - name: check aws cli version
    shell: aws --version
    register: aws_version_output
    become_user: ubuntu
    environment:
      HOME: /home/ubuntu
      AWS_SHARED_CREDENTIALS_FILE: /home/ubuntu/.aws/credentials

  - name: show awscli version
    debug:
      var: aws_version_output.stdout
